export interface ProductFeature {
  title: string
  description: string
  icon?: string
}

export interface TechnicalSpec {
  label: string
  value: string
}

export interface ProductModel {
  name: string
  pitch: string
  ledType: string
  brightness: string
  transparency?: string
  refreshRate: string
  powerMax: string
}

export interface Product {
  id: string
  slug: string
  name: string
  series: string
  category: string
  image: string
  gallery: string[]
  description: string
  longDescription: string
  features: ProductFeature[]
  specs: TechnicalSpec[]
  models?: ProductModel[]
  buyable: boolean
  price: number | null
  unit: string | null
}

export const products: Product[] = [
  {
    id: "outdoor-of",
    slug: "outdoor-fixed-led-display",
    name: "Outdoor Fixed LED Display",
    series: "OF Series",
    category: "Outdoor",
    image: "/images/products/outdoor-fixed-led-display.jpg",
    gallery: ["/images/products/outdoor-fixed-led-display.jpg"],
    description: "High-performance outdoor LED billboard for permanent installations — building facades, rooftops, and large-scale advertising with 8000 nits brightness and IP65 protection.",
    longDescription: "The OF Series Outdoor Fixed LED Display is engineered for the world's most demanding permanent installation environments. Using precision die-cast magnesium alloy cabinets — 30% thinner than iron and 40% lighter than standard aluminum — our displays sit at just 120mm depth while delivering up to 8,000 nits of blazing brightness. With seamless pixel-perfect cabinet joins and dual front/rear service access, the OF Series is ideal for landmark billboards, building facades, shopping center exteriors, airport signage, highway advertisements, and stadium perimeters. The IP65 rating guarantees stable operation through heavy rain, coastal salt air, desert sand, and temperatures ranging from -40°C to +60°C. Every model features a built-in brightness sensor that automatically adjusts output for ambient light conditions — saving energy at night while remaining vivid in midday sun.",
    features: [
      { title: "IP65 Full Weatherproofing", description: "Sealed die-cast cabinet endures rain, sand, humidity, and temperatures from -40°C to +60°C without performance degradation." },
      { title: "Up to 8,000 nits Brightness", description: "Engineered to remain fully visible under direct midday sunlight. Custom 10,000 nit models available for extreme exposure environments." },
      { title: "Die-Cast Magnesium Cabinet", description: "30% thinner than iron cabinets, 40% lighter than standard aluminum — precision engineered for zero-gap seamless joins." },
      { title: "Front & Rear Service", description: "Modules, power supplies, and receiving cards can be replaced from either the front or back of the display — minimizing downtime." },
      { title: "Auto Brightness Sensor", description: "Built-in ambient light sensor automatically dims the display at night and brings it to full power at dawn. Saves up to 40% energy." },
      { title: "Multiple Billboard Formats", description: "Compatible with wall-mounted, rooftop, street pole, dual-sided, and triangle LED billboard configurations." },
      { title: "High Refresh Rate", description: "≥3840Hz refresh rate ensures flicker-free visuals when captured by broadcast cameras, dashcams, or smartphone cameras." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P4 - P10" },
      { label: "Brightness", value: "6,500 – 8,000 nits (up to 10,000 nits custom)" },
      { label: "Refresh Rate", value: "≥3840Hz" },
      { label: "IP Rating", value: "IP65 Front & Rear" },
      { label: "Cabinet Depth", value: "120mm" },
      { label: "Operating Temperature", value: "-40°C to +60°C" },
      { label: "Viewing Angle", value: "H: 140° / V: 140°" },
      { label: "Lifespan", value: "100,000+ Hours" },
    ],
    models: [
      { name: "OF4", pitch: "4mm", ledType: "SMD1921 Black", brightness: "6500 nits", refreshRate: "3840Hz", powerMax: "800W/m²" },
      { name: "OF6", pitch: "6.67mm", ledType: "SMD2727", brightness: "7500 nits", refreshRate: "3840Hz", powerMax: "750W/m²" },
      { name: "OF10", pitch: "10mm", ledType: "DIP346", brightness: "8000 nits", refreshRate: "1920Hz", powerMax: "700W/m²" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "rental-ro",
    slug: "outdoor-rental-led-display",
    name: "Outdoor Rental LED Display",
    series: "RO Series",
    category: "Rental",
    image: "/images/products/outdoor-rental-led-display.jpg",
    gallery: ["/images/products/outdoor-rental-led-display.jpg"],
    description: "Professional outdoor rental LED display with 5,500 nits brightness. High contrast black SMD LEDs for stunning stage visuals at concerts, festivals, and corporate events.",
    longDescription: "The RO Series Outdoor Rental LED Display is the industry benchmark for large-scale outdoor events. Each cabinet in the standard 500×500mm format weighs just 7.5kg and locks securely in seconds with a tool-free auto-lock mechanism — allowing small crews to build towering video walls in record time. Black SMD LED technology produces a 5000:1 contrast ratio that makes colors pop even under harsh afternoon sunlight on open-air festival stages. The die-cast aluminum cabinets achieve ±15° inner and outer arc for curved stage backdrops and S-wave configurations. Both hanging (up to 10m high) and ground-stacking modes are supported with matching rigging hardware. The 3840Hz refresh rate ensures every broadcast camera captures crisp, flicker-free footage — essential for live TV and online streaming productions.",
    features: [
      { title: "Auto-Lock Fast Assembly", description: "Each cabinet snaps together with a single-action auto-lock — no tools, no bolts. A crew of 2 can build a 100m² wall in under 3 hours." },
      { title: "5,500 nits Outdoor Brightness", description: "Perfectly visible in direct afternoon sunlight during outdoor festivals. Black SMD ensures deep blacks and vivid contrast simultaneously." },
      { title: "7.5kg Ultra-Light Cabinet", description: "Die-cast aluminum 500×500mm panels at just 7.5kg each — dramatically reducing truss load, transport costs, and labor." },
      { title: "±15° Arc Flexibility", description: "Inner concave and outer convex curving up to 15° — create stunning curved backdrops, S-waves, and wrap-around stage designs." },
      { title: "3840Hz Broadcast Ready", description: "High refresh rate driving IC ensures no flicker on any broadcast, streaming, or social media camera." },
      { title: "Safe Hanging & Stacking", description: "Certified hanging and ground-stacking up to 20 panels high (10m) with compatible truss and base structures." },
      { title: "5000:1 Contrast Ratio", description: "Black SMD LEDs deliver deep, rich blacks alongside bright highlights — cinematic image quality for any live production." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P3.91 / P4.81 / P6.25" },
      { label: "Brightness", value: "5,500 nits" },
      { label: "Contrast Ratio", value: "5000:1" },
      { label: "Cabinet Size", value: "500×500mm / 500×1000mm" },
      { label: "Cabinet Weight", value: "7.5kg (500×500mm)" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Max Stack Height", value: "10m (20 panels)" },
      { label: "IP Rating", value: "IP65 Front" },
    ],
    models: [
      { name: "RO3.9", pitch: "3.91mm", ledType: "SMD1921 Black", brightness: "5500 nits", refreshRate: "3840Hz", powerMax: "600W/m²" },
      { name: "RO4.8", pitch: "4.81mm", ledType: "SMD1919 Black", brightness: "5500 nits", refreshRate: "3840Hz", powerMax: "550W/m²" },
      { name: "RO6.2", pitch: "6.25mm", ledType: "SMD2727 Black", brightness: "5500 nits", refreshRate: "1920Hz", powerMax: "500W/m²" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "transparent-ts",
    slug: "transparent-led-screen",
    name: "Transparent LED Screen",
    series: "TS Series",
    category: "Transparent",
    image: "/images/products/transparent-led-screen.jpg",
    gallery: ["/images/products/transparent-led-screen.jpg"],
    description: "See-through LED screen with up to 85% transparency and 5,500 nits brightness — seamlessly integrated into glass facades, retail stores, showrooms, and event stages.",
    longDescription: "The TS Series Transparent LED Screen is redefining how brands communicate through glass. By retaining 65–85% transparency, buildings maintain their open, airy feel while displaying dynamic full-color video to the outside world. In retail environments, these screens transform floor-to-ceiling windows into billboard-scale media without obscuring the product view inside. In corporate lobbies and showrooms, they create a premium 'floating display' effect that traditional screens cannot replicate. The film version (3mm thin, 3kg/m²) uses a self-adhesive PET base to bond directly to any glass panel in hours — no structural changes needed. Brightness up to 5,500 nits ensures that even in bright atrium environments or semi-outdoor settings, the content remains vivid and compelling.",
    features: [
      { title: "Up to 85% Transparency", description: "Maintains the building's natural aesthetic and interior/exterior visibility. Natural daylight still flows through the display when idle." },
      { title: "5,500 nits Brightness", description: "Clearly visible through glass in bright indoor atriums and semi-outdoor canopied environments." },
      { title: "Self-Adhesive Film Option", description: "3mm-thin PET film version adheres directly to any glass panel — 3kg/m² weight, no drilling or structural work required." },
      { title: "Modular Rigid Panels", description: "Rigid panel version allows large-scale glass facade installations with precise grid alignment and front/rear maintenance access." },
      { title: "Custom Shapes & Sizes", description: "Modular design can be cut or combined to cover any glass shape — arches, triangles, irregular polygons, and curved glass." },
      { title: "High Resolution Options", description: "P2.6mm pitch provides detailed HD imagery for close-passing viewers in shopping malls and airports." },
    ],
    specs: [
      { label: "Transparency", value: "65% – 85%" },
      { label: "Pixel Pitch", value: "P2.6 – P7.8" },
      { label: "Brightness", value: "4,500 – 5,500 nits" },
      { label: "Film Thickness", value: "3mm (film version)" },
      { label: "Film Weight", value: "3 kg/m²" },
      { label: "Refresh Rate", value: "≥3840Hz" },
      { label: "Installation", value: "Self-adhesive / Frame mount" },
      { label: "Lifespan", value: "50,000+ Hours" },
    ],
    models: [
      { name: "TS2.6", pitch: "2.6-5.2mm", ledType: "SMD1515", brightness: "4500 nits", transparency: "70%", refreshRate: "3840Hz", powerMax: "600W/m²" },
      { name: "TS3.9", pitch: "3.9-7.8mm", ledType: "SMD1919", brightness: "5500 nits", transparency: "80%", refreshRate: "3840Hz", powerMax: "550W/m²" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "flexible-fd",
    slug: "flexible-led-display",
    name: "Flexible LED Display",
    series: "FD Series",
    category: "Creative",
    image: "/images/products/flexible-led-display.jpg",
    gallery: ["/images/products/flexible-led-display.jpg"],
    description: "Soft-module LED display made from flexible PCB and rubber material — bends into any creative shape including cylinders, waves, S-curves, and spheres.",
    longDescription: "The FD Series Flexible LED Display breaks every constraint of the flat rectangle. Built using high-density flexible PCBs bonded to a silicone rubber mask, each module can be gently bent to a minimum radius of 150mm — creating seamless cylinders, S-waves, concave arcs, and compound-curved surfaces that rigid cabinets simply cannot achieve. At just 10mm thick and under 1kg per module, it imposes virtually zero structural load and can be adhered, hung, or magnetically attached to almost any surface. The magnetic mounting system means two technicians can dress an entire curved stage column in minutes. Front maintenance is fully supported — a technician can swap any faulty tile without dismantling surrounding panels. Creative applications include LED reception columns, curved ceiling installations, immersive tunnel displays, wave-shaped stage elements, and artistic media art.",
    features: [
      { title: "150mm Min Bend Radius", description: "Bend into tight cylinders, S-curves, wave shapes, and compound surfaces — without cracking or distorting the display." },
      { title: "10mm Ultra-Slim", description: "Only 10mm total thickness and under 1kg per module — installs on any substrate without structural reinforcement." },
      { title: "Magnetic Attachment", description: "Built-in magnets snap modules securely to steel surfaces in seconds — no screws, no tools." },
      { title: "Front Service Access", description: "Individual tiles can be removed and replaced from the front — ideal for complex installations where rear access is impossible." },
      { title: "High Visual Quality", description: "High-density SMD LEDs deliver excellent color uniformity and brightness even on curved surfaces." },
      { title: "Creative Architecture", description: "Perfect for LED columns, arched entrances, wave-shaped backdrops, tunnel displays, and decorative ceiling media art." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P1.56 – P5" },
      { label: "Thickness", value: "10mm" },
      { label: "Weight", value: "<1kg per module" },
      { label: "Min Bend Radius", value: "150mm" },
      { label: "Maintenance", value: "Front Service" },
      { label: "Refresh Rate", value: "≥3840Hz" },
      { label: "Mounting", value: "Magnetic / Screw / Hang" },
      { label: "Lifespan", value: "50,000+ Hours" },
    ],
    models: [
      { name: "FD1.5", pitch: "1.56mm", ledType: "SMD1010", brightness: "1200 nits", refreshRate: "3840Hz", powerMax: "500W/m²" },
      { name: "FD2.5", pitch: "2.5mm", ledType: "SMD1515", brightness: "1500 nits", refreshRate: "3840Hz", powerMax: "450W/m²" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "neon-custom",
    slug: "custom-neon-led-sign",
    name: "Custom Neon LED Sign",
    series: "Neon LED",
    category: "Neon LED",
    image: "/images/products/shop-window-led-display.jpg",
    gallery: ["/images/products/shop-window-led-display.jpg"],
    description: "Bespoke LED neon signs for restaurants, bars, retail stores, events, and home decor — any font, logo, or shape, made to order.",
    longDescription: "Our Custom LED Neon Signs deliver the iconic warm glow of traditional glass neon — but with none of the fragility, hazardous gases, or sky-high power bills. Handcrafted using premium flexible silicone LED tubing, each sign is shatterproof, stays cool to the touch, and runs at 12V or 24V for safety in any environment. The signs are mounted on premium acrylic or brushed metal backing boards and come ready to hang with pre-drilled fixings. Popular for restaurant feature walls, bar signage, retail window displays, wedding backdrops, studio branding walls, and personalized gifts. Full custom quoting available for any shape, size, font, or color — typically produced in 10–15 business days.",
    features: [
      { title: "Fully Custom Shape", description: "Any text, logo, icon, or abstract shape can be realized in LED neon — from simple words to complex brand logos." },
      { title: "80% Energy Saving", description: "Consumes up to 80% less electricity than traditional glass neon tubes of equivalent size." },
      { title: "Shatterproof Silicone", description: "Flexible silicone tubing — no glass to crack, no toxic gases, safe for children's spaces and busy public environments." },
      { title: "Cool to the Touch", description: "Stays cool even after hours of operation — safe for close customer contact in retail and hospitality settings." },
      { title: "Premium Backing Options", description: "Choice of clear acrylic, frosted acrylic, or brushed metal backing for different aesthetic effects." },
      { title: "Indoor & Outdoor", description: "IP65-rated models available for outdoor patio signage, shopfronts, and exterior branding." },
    ],
    specs: [
      { label: "Input Voltage", value: "12V / 24V DC" },
      { label: "Lifespan", value: "50,000+ Hours" },
      { label: "Backing Options", value: "Acrylic / Brushed Metal / Wood" },
      { label: "Application", value: "Indoor / Outdoor (IP65)" },
      { label: "Color Options", value: "White, Warm White, Red, Blue, Green, Pink, Purple, RGB" },
      { label: "Production Time", value: "10–15 Business Days" },
      { label: "Mounting", value: "Pre-drilled wall fixings included" },
      { label: "Dimming", value: "Dimmable (0–100%)" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "mobile-truck-new",
    slug: "mobile-truck-led-display",
    name: "Mobile Truck LED Display",
    series: "MT Series",
    category: "Mobile",
    image: "/images/products/mobile-truck-led-display.jpg",
    gallery: ["/images/products/mobile-truck-led-display.jpg"],
    description: "High-impact mobile billboard on trucks and trailers — 6,500 nits, GPS tracking, 4G remote control, and live broadcast capability for maximum street-level advertising reach.",
    longDescription: "The MT Series Mobile Truck LED Display turns any commercial truck or trailer into a moving landmark billboard. Unlike printed vinyl wraps, a digital truck display can show multiple advertisers per day, update content remotely via 4G cloud, or stream live sports and events via a connected video processor. At 6,500 nits standard brightness, the billboard remains fully legible in glaring afternoon sun on motorways and busy intersections. Built-in shock absorption handles the constant vibration of motorway driving without damaging LEDs or connections. Wide-voltage input (9V—36V DC) is compatible with the electrical systems of all major truck and trailer manufacturers. Optional GPS integration enables geo-targeted advertising: specific content plays when the truck enters predetermined geographic zones.",
    features: [
      { title: "6,500 nits Street Brightness", description: "Fully visible from 50m+ in direct sunlight — commands attention at busy intersections and motorway turnoffs." },
      { title: "4G Cloud Content Updates", description: "Push new ads to your entire fleet instantly via the cloud — perfect for time-sensitive campaigns and daily schedule changes." },
      { title: "Shock-Proof Cabinets", description: "Reinforced mounting and shock-absorbing internal structure prevents LED damage from road vibrations and speed bumps." },
      { title: "Live TV / Streaming", description: "Connect a video processor to stream live sports, events, or news broadcasts directly on the road." },
      { title: "GPS Geo-Targeting", description: "Trigger location-specific content automatically as the truck enters specified neighborhoods or proximity to landmarks." },
      { title: "Auto Brightness Control", description: "Ambient light sensor dims the display at night and raises it to full power in daylight — no manual adjustment needed." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P3.91 – P8" },
      { label: "Brightness", value: "6,500 nits" },
      { label: "Refresh Rate", value: "≥1920Hz" },
      { label: "Protection", value: "IP65 Waterproof" },
      { label: "Input Voltage", value: "9V – 36V DC" },
      { label: "Control", value: "4G / WiFi / USB / HDMI" },
      { label: "Configurations", value: "1-sided / 2-sided / 3-sided" },
      { label: "GPS Tracking", value: "Optional (Built-in)" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "creative-cylinder",
    slug: "cylinder-led-display",
    name: "Can Shape Cylinder LED Display",
    series: "CA Series",
    category: "Creative",
    image: "/images/products/can-shape-cylinder-led-display.jpg",
    gallery: ["/images/products/can-shape-cylinder-led-display.jpg"],
    description: "360° seamless cylinder LED display — iconic can-shaped brand installations for beverage companies, retail experiences, and landmark events.",
    longDescription: "The CA Series Cylinder LED Display is the signature product for brands that want their retail presence to become a spectacle. Designed to replicate the shape of a can or column, each cylinder is assembled from purpose-built flexible PCB modules that wrap precisely to form a perfectly smooth, gapless surface with true 360° visibility. Content appears vivid and uniform whether a passerby is directly in front or standing behind the display. Standard pixel pitches from P1.8mm to P4mm for indoor use; outdoor cylindrical displays from P4mm to P6mm with IP65 protection. Diameter and height are fully customizable. Power and data run through concealed internal channels. Installation options include freestanding with a weighted base or ceiling-hung from a single suspension point. Popular deployments include Pepsi and Coca-Cola promotional pillars, hotel lobby columns, and museum interactive media.",
    features: [
      { title: "Seamless 360° Uniform Display", description: "Trapezoidal module geometry ensures perfect pixel alignment with no gaps or visible joins from any direction." },
      { title: "Fully Customizable Dimensions", description: "Diameter from 300mm to 2,000mm+; height from 500mm to 3,000mm+. Any brand specification delivered." },
      { title: "Freestanding or Ceiling-Hung", description: "Heavy weighted base for floor installations or single-point ceiling suspension for floating column effect." },
      { title: "Plug & Play Media Player", description: "Built-in asynchronous player with WiFi and USB support — no PC needed for standalone content looping." },
      { title: "Indoor & Outdoor Models", description: "Indoor P1.8–P4 for showrooms and malls; outdoor P4–P6 with IP65 for plazas and event exteriors." },
      { title: "Concealed Cable Routing", description: "All power and data cabling runs through the internal column structure — no visible wires." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P1.8 – P6 (Indoor & Outdoor)" },
      { label: "Typical Diameter", value: "500mm – 2000mm (Custom)" },
      { label: "Typical Height", value: "500mm – 3000mm (Custom)" },
      { label: "Brightness", value: "1000 nits (Indoor) / 5000 nits (Outdoor)" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Installation", value: "Freestanding / Ceiling Hung" },
      { label: "IP Rating", value: "IP20 (Indoor) / IP65 (Outdoor)" },
      { label: "Control", value: "USB / WiFi / 4G" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "digital-poster",
    slug: "digital-led-poster",
    name: "HD Digital LED Poster",
    series: "DP Series",
    category: "Indoor",
    image: "/images/products/hd-digital-led-poster.jpg",
    gallery: ["/images/products/hd-digital-led-poster.jpg"],
    description: "Ultra-slim portable LED banner display — the modern replacement for the traditional roll-up banner, with plug-and-play simplicity and multi-screen splicing capability.",
    longDescription: "The DP Series HD Digital LED Poster elevates any retail, event, or exhibition setup from static to dynamic in minutes. Standing at 1920×640mm with a 1mm aluminum frame bezel and just 35mm of depth, it disappears at a glance to let the content shine. Each unit comes with integrated wheels for effortless repositioning between venues. The built-in media player auto-plays content as soon as a USB stick is inserted — no software, no configuration, no technician. For large-scale deployments, 6 units tile together for a widescreen 16:9 display or 10 units assemble into a full HD 1920×1080 wall. The display supports live streaming from a laptop via HDMI, remote management over LAN/WiFi from a mobile app, and optional 4G for cloud-based content scheduling. Every unit ships with a robust flight case for frequent transport and a honeycomb protective box for fixed installations.",
    features: [
      { title: "Plug & Play via USB", description: "Insert a USB stick and the poster auto-plays your content immediately — no PC, no software configuration required." },
      { title: "Tile Up to 10 Units", description: "6 units = widescreen 16:9; 10 units = full HD 1080P video wall with a built-in synchronization processor." },
      { title: "1mm Bezel Ultra-Slim Frame", description: "1mm aluminum frame makes the poster nearly bezel-free when multiple units are tiled together for a large display." },
      { title: "Built-In Wheels", description: "Integrated caster wheels allow one person to reposition the poster anywhere without lifting — perfect for live events." },
      { title: "HDMI Live Input", description: "Connect a laptop or media player via HDMI for real-time live streaming at product launches and press events." },
      { title: "Multi-Control Options", description: "HDMI / LAN / WiFi / USB / optional 4G. Manage all units on a network from a single mobile app." },
      { title: "Flight Case Transport", description: "Each unit ships with a protective flight case — ideal for rental businesses and frequent exhibition use." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P1.6 / P2 / P2.5 / P3" },
      { label: "Dimensions", value: "1920×640mm (Standard)" },
      { label: "Frame Bezel", value: "1mm Aluminum" },
      { label: "Thickness", value: "35mm" },
      { label: "Weight", value: "28 – 30 kg per unit" },
      { label: "Brightness", value: "1,200 nits" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Control", value: "USB / HDMI / WiFi / LAN / 4G (Optional)" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "taxi-top",
    slug: "taxi-top-led-display",
    name: "HD Full Color Taxi Top LED Display",
    series: "TD Series",
    category: "Mobile",
    image: "/images/products/hd-full-color-taxi-top-led-display.jpg",
    gallery: ["/images/products/hd-full-color-taxi-top-led-display.jpg"],
    description: "Aerodynamic rooftop LED advertising display for taxis with 5,000–5,500 nits brightness, GPS geo-targeting, 4G cloud control, and IP56 all-weather protection.",
    longDescription: "The TD Series Taxi Top LED Display is the gold standard of taxi advertising media. Aerodynamically profiled to minimize drag and wind noise, each unit mounts securely to any standard roof rack with a screwdriver in under 20 minutes. Three pixel pitch options (P2.5, P3.33, P5) provide a brightness range of 4,500–5,500 nits, ensuring the display is always legible — in blazing midday sun or low evening light. The IP56-rated enclosure is fully weatherproof and shock-resistant. Electrostatic and lightning protection systems are built in for durability in all city weather conditions. 4G connectivity enables fleet-wide content updates from a single cloud dashboard. GPS real-time tracking lets advertisers run geo-targeted campaigns — different creative plays automatically when the taxi enters different neighborhoods, business districts, or event zones. Smart power management draws minimal current from the vehicle's alternator, with built-in over-voltage protection.",
    features: [
      { title: "GPS Geo-Targeted Advertising", description: "Run location-specific content automatically — show restaurant ads near food districts, event promotions near venues." },
      { title: "5,500 nits Daylight Brightness", description: "Fully legible in direct sun at any time of day. P5 model hits 5,500 nits for maximum street impact." },
      { title: "IP56 All-Weather Housing", description: "Waterproof, shockproof, with electrostatic and lightning protection — survives any city weather condition." },
      { title: "4G Fleet Management", description: "Update content on every vehicle simultaneously via cloud dashboard — schedule campaigns by time of day and vehicle." },
      { title: "20-Minute Roof Rack Install", description: "Mounts to any standard taxi roof rack with just a screwdriver — no drilling, no electrician required." },
      { title: "Smart Power Management", description: "Extremely low current draw from the vehicle alternator with over-voltage protection built in." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P2.5 / P3.33 / P5" },
      { label: "Brightness", value: "4,500 – 5,500 nits" },
      { label: "Protection", value: "IP56 Weatherproof" },
      { label: "Input Voltage", value: "9V – 36V DC" },
      { label: "Shell Material", value: "Die-casting Aluminum" },
      { label: "Control", value: "4G / WiFi / GPS" },
      { label: "Operating Temperature", value: "-40°C to +75°C" },
      { label: "Installation", value: "Universal Roof Rack (Screwdriver Only)" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "sphere-sp",
    slug: "sphere-led-display",
    name: "Sphere LED Display",
    series: "SP Series",
    category: "Creative",
    image: "/images/products/sphere-led-display.jpg",
    gallery: ["/images/products/sphere-led-display.jpg"],
    description: "Full 360° spherical LED display — the ultimate showpiece for shopping malls, museums, planetariums, and landmark brand installations. Sizes from 0.6m to 5m+ diameter.",
    longDescription: "The SP Series Sphere LED Display is engineering art. Each sphere is assembled from hundreds of trapezoidal and triangular flexible LED modules that interlock to form a perfectly smooth, seamless spherical surface. Unlike flat screens, this display is visible in full from every direction simultaneously — eliminating dead viewing angles and drawing crowds from across a room. Indoor models range from P1.56mm fine-pitch for exquisite close-range detail, to P4mm for larger diameters. Outdoor IP68 models start at P5mm and are fully submerge-proof. Standard diameters ship from 0.8m to 2m; entirely custom diameters from 0.3m to 5m+ are available with a 30-day lead time. Half-sphere and dome configurations available from 1m diameter. Every sphere supports synchronous and asynchronous content modes — play looping brand videos without a PC, or connect live sources via HDMI.",
    features: [
      { title: "Full Seamless 360° Surface", description: "Trapezoidal circuit design achieves perfect pixel density and flatness with zero visible joints from any direction." },
      { title: "Undistorted Visual Quality", description: "Uniform tapping technology preserves image geometry — no warping or stretching on the curved surface." },
      { title: "Fine Pitch Indoor: P1.56–P4", description: "Finest available at P1.56mm for ultra-close viewing in museums and showrooms; up to P4 for large public installations." },
      { title: "Outdoor IP68 Models", description: "Fully waterproof outdoor sphere from P5–P10 for permanent exterior brand landmarks and plaza centerpieces." },
      { title: "Half-Sphere Option", description: "Dome or half-sphere configurations available from 1m diameter — ideal for ceiling-mounted installations." },
      { title: "Flexible Installation", description: "Freestanding weighted base, ceiling suspension, or wall bracket — designed for any architectural context." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P1.56 – P4 (Indoor) / P5 – P10 (Outdoor)" },
      { label: "Diameter", value: "0.6m – 5m+ (Custom)" },
      { label: "Brightness", value: "1,000 nits (Indoor) / 6,500 nits (Outdoor)" },
      { label: "Refresh Rate", value: "≥3840Hz" },
      { label: "IP Rating", value: "IP20 Indoor / IP68 Outdoor" },
      { label: "Maintenance", value: "Partial Front Access" },
      { label: "Control", value: "USB / WiFi / HDMI" },
      { label: "Configurations", value: "Full Sphere / Half Sphere / Dome" },
    ],
    models: [
      { name: "SP2", pitch: "2mm", ledType: "SMD1515", brightness: "1000 nits", refreshRate: "3840Hz", powerMax: "800W/m²" },
      { name: "SP4", pitch: "4mm", ledType: "SMD2020", brightness: "1200 nits", refreshRate: "3840Hz", powerMax: "700W/m²" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "cube-cl",
    slug: "cube-led-display",
    name: "Cube LED Display",
    series: "CL Series",
    category: "Creative",
    image: "/images/products/cube-led-display.jpg",
    gallery: ["/images/products/cube-led-display.jpg"],
    description: "Multi-sided LED video cube with 4, 5, or 6 seamless faces — a 360° visible digital centrepiece for retail, exhibitions, events, and flagship brand spaces.",
    longDescription: "The CL Series Cube LED Display is the premium statement piece for brands and venues who demand a futuristic, multi-dimensional screen presence. Available in 4, 5, or 6-sided configurations, every face displays HD content — the same video synchronised across all sides, or independent creative per face. With fine pitch options from P1.25mm to P3mm, even a 500×500mm cube delivers near-retina resolution. The 5 and 6-sided variants support spectacular naked-eye 3D effects using purpose-built content that appears to float inside the cube. A built-in plug-and-play media player starts content automatically on power-up — no video processor required. Outdoor models at P2.5–P3.91 feature IP65 protection and front-access servicing for building exterior applications. Side lengths from 320mm to custom 2000mm+ available.",
    features: [
      { title: "4, 5, or 6-Sided Seamless Cube", description: "Custom die-cast frame joins all faces with ultra-fine gaps — uniform brightness and color match across every side." },
      { title: "Naked-Eye 3D on 5/6 Sides", description: "5 and 6-sided cubes display 3D floating object effects visible from any angle — without glasses or special screens." },
      { title: "Built-In Plug & Play Player", description: "No external video processor needed. Auto-plays video, photos, and animations from USB or WiFi on power-up." },
      { title: "Outdoor IP65 Option", description: "Weatherproof outdoor cube from P2.5–P3.91 for exterior storefronts, plazas, and exposed event areas." },
      { title: "Custom Side Lengths", description: "Standard 320–800mm sides; fully custom up to 2000mm+ for flagship retail and landmark installations." },
      { title: "Hanging, Standing, or Wall", description: "Compatible with ceiling suspension, freestanding pole mount, and wall-bracket configurations." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P1.25 – P4 (Indoor) / P2.5 – P3.91 (Outdoor)" },
      { label: "Typical Side Length", value: "320mm – 800mm (Custom up to 2000mm+)" },
      { label: "Configurations", value: "4-Sided / 5-Sided / 6-Sided" },
      { label: "Brightness", value: "800 – 1,000 nits (Indoor)" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Cabinet", value: "Die-casting Aluminum" },
      { label: "IP Rating", value: "IP20 (Indoor) / IP65 (Outdoor)" },
      { label: "Control", value: "USB / WiFi / HDMI" },
    ],
    models: [
      { name: "CL1.5", pitch: "1.5mm", ledType: "SMD1010", brightness: "800 nits", refreshRate: "3840Hz", powerMax: "600W/m²" },
      { name: "CL2.5", pitch: "2.5mm", ledType: "SMD1515", brightness: "1000 nits", refreshRate: "3840Hz", powerMax: "550W/m²" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "curtain-lc",
    slug: "led-curtain-display",
    name: "LED Curtain Display",
    series: "LC Series",
    category: "Advertising",
    image: "/images/products/led-curtain-display.JPG",
    gallery: ["/images/products/led-curtain-display.JPG"],
    description: "Transparent mesh LED curtain for large building facades, bridges, and architectural landmarks — ultra-lightweight 15kg/m², IP67 waterproof, up to 10,000 nits.",
    longDescription: "The LC Series LED Curtain Display is the go-to solution for large-scale architectural media installations that need to cover immense surfaces while retaining visual transparency and minimizing structural load. At just 15kg/m² — 75% lighter than traditional iron outdoor cabinet displays — it can be applied to glass facades, open steel frameworks, bridges, and tower exteriors with minimal engineering reinforcement. The aluminium cabinet is 60mm deep and integrates power supply and controller in one unit, simplifying wiring to a single trunk cable. SMD versions deliver 6,500 nits; DIP versions reach 10,000 nits for direct-sun coastal installations. With 40–80% optical transparency and IP67 full protection, curtain installations perform magnificently day and night, through monsoons and dust storms.",
    features: [
      { title: "15kg/m² — 75% Lighter", description: "Only 15kg per square metre — 75% lighter than traditional iron cabinets. Dramatically reduces structural reinforcement cost on high-rise facades." },
      { title: "Up to 10,000 nits (DIP)", description: "SMD version at 6,500 nits; DIP version at 10,000 nits for coastal or hillside installations in direct sunlight." },
      { title: "40%–80% Wind-Transparent Mesh", description: "Mesh structure reduces wind load on high-rise facades while maintaining 40–80% visual transparency for natural building aesthetics." },
      { title: "IP67 Full Weatherproofing", description: "Full-glue PCB cover and waterproof rubber ring: IP67. Operates from -40°C to +60°C year-round in any climate." },
      { title: "135W/m² Low Power Cost", description: "Exceptionally energy-efficient — 135W/m² average vs 300W/m²+ for traditional outdoor fixed displays." },
      { title: "60mm Slim Integrated Cabinet", description: "Power supply and controller housed within the 60mm cabinet depth. Single trunk cable installation dramatically simplifies on-site wiring." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P15.6 – P31.25" },
      { label: "Brightness", value: "6,500 nits (SMD) / 10,000 nits (DIP)" },
      { label: "Transparency", value: "40% – 80%" },
      { label: "Weight", value: "15 kg/m²" },
      { label: "Cabinet Depth", value: "60mm" },
      { label: "Power Consumption", value: "135W/m² (Average)" },
      { label: "IP Rating", value: "IP67" },
      { label: "Refresh Rate", value: "≥1920Hz" },
    ],
    models: [
      { name: "LC15", pitch: "15.625mm", ledType: "DIP346", brightness: "8500 nits", refreshRate: "1920Hz", powerMax: "600W/m²" },
      { name: "LC25", pitch: "25mm", ledType: "DIP346", brightness: "10000 nits", refreshRate: "1920Hz", powerMax: "550W/m²" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "dance-floor-df",
    slug: "led-dance-floor",
    name: "LED Dance Floor",
    series: "DF Series",
    category: "Rental",
    image: "/images/products/led-dance-floor.jpg",
    gallery: ["/images/products/led-dance-floor.jpg"],
    description: "Rugged HD LED dance floor for nightclubs, weddings, concerts, and stage productions — 2,000kg/m² load capacity, anti-slip surface, and IP65 waterproofing for indoor and outdoor events.",
    longDescription: "The DF Series LED Dance Floor transforms any event floor into a living, breathing visual experience. Each 500×500mm aluminium die-cast tile is just 80mm tall and 9kg — light enough for small crews to set up large floors in hours, yet engineered to support 2,000kg/m², making it safe for packed dance floors, performers in heels, heavy props, and even light vehicles for industrial events. The anti-slip high-strength PC glass surface is tested to international slip-resistance standards. Advanced glue-filling technology seals the PCB and all module seams to IP65, meaning the floor can be safely used at outdoor festivals and pool-deck events in rain. Front maintenance access allows technicians to swap any tile from above without lifting adjacent panels — vital during multi-day events. Content can be fully interactive with optional pressure sensors that trigger zone-specific animations in real time as performers dance.",
    features: [
      { title: "2,000kg/m² Load Capacity", description: "Independently tested to support cars, crowd loads, and heavy stage equipment safely without deformation." },
      { title: "Anti-Slip Safety Surface", description: "High-strength tempered PC glass top layer with anti-slip coating — certified safe for dancers and high heels." },
      { title: "IP65 Waterproof", description: "Advanced PCB encapsulation and rubber ring sealing provides full IP65 protection for outdoor events and pool decks." },
      { title: "Fast Front Maintenance", description: "Any tile replaced from above without dismantling neighbours — critical for fast recovery during multi-day productions." },
      { title: "Interactive Sensor Option", description: "Optional pressure sensors enable real-time zone animations triggered by dancers' steps for immersive experiences." },
      { title: "9kg Ultra-Light Tiles", description: "Each 500×500mm tile at just 9kg. Two people can lay 50m² in under 2 hours." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P2.9 – P6.25" },
      { label: "Load Capacity", value: "2,000 kg/m²" },
      { label: "Cabinet Size", value: "500×500mm / 500×1000mm" },
      { label: "Tile Thickness", value: "80mm" },
      { label: "Tile Weight", value: "9kg per 500×500mm tile" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "IP Rating", value: "IP65 (Indoor & Outdoor)" },
      { label: "Surface", value: "Anti-Slip PC Glass" },
    ],
    models: [
      { name: "DF3.9", pitch: "3.91mm", ledType: "SMD1919Black", brightness: "1200 nits", refreshRate: "3840Hz", powerMax: "700W/m²" },
      { name: "DF6.2", pitch: "6.25mm", ledType: "SMD1919Black", brightness: "1200 nits", refreshRate: "3840Hz", powerMax: "650W/m²" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "delivery-box",
    slug: "food-delivery-box-led",
    name: "Food Delivery Box LED",
    series: "DB Series",
    category: "Mobile",
    image: "/images/products/food-delivery-box-led.png",
    gallery: ["/images/products/food-delivery-box-led.png"],
    description: "3-sided mobile LED billboard for delivery motorcycles and cargo bikes — 5,000 nits, GPS geo-targeting, 4G cloud management, and 270° city-wide visibility.",
    longDescription: "The DB Series Food Delivery Box LED Display turns every delivery ride into a revenue-generating mobile advertising campaign. Left, right, and rear faces display full-color HD content simultaneously, delivering 270° audience coverage in crowded city streets. The unit is powered by the motorcycle battery (12V–24V DC) and runs for 6–8 hours continuously without noticeable power drain. At 5,000 nits, the display is vivid under direct midday sun. Integrated GPS real-time tracking allows advertisers to purchase geo-targeted campaigns: different ads play automatically when the delivery enters specific neighborhoods, high-street zones, or proximity to target stores. 4G connectivity enables the display to receive new campaign content in real time. The robust IP65-rated aluminum housing is designed to survive the daily rigours of urban delivery routes — vibrations, rain, and dust.",
    features: [
      { title: "3-Sided 270° Visibility", description: "Left, right, and rear LED faces display the same or different content simultaneously — seen by pedestrians, cyclists, and motorists." },
      { title: "5,000 nits Daylight Bright", description: "Brilliant visual impact under direct sunlight on any busy street or high-traffic intersection." },
      { title: "GPS Geo-Targeted Campaigns", description: "Serve different ad content automatically as the delivery enters specified neighborhoods or proximity zones." },
      { title: "4G Real-Time Cloud Update", description: "Content pushed remotely to the entire fleet simultaneously — schedule and change campaigns without any physical access." },
      { title: "6–8 Hour Battery Runtime", description: "Draws power directly from the motorcycle battery at 12V–24V DC. Minimal drain — compatible with all standard delivery vehicles." },
      { title: "IP65 Rugged Housing", description: "Weatherproof, shockproof aluminium body built for the daily rigour of urban delivery routes." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P2.5 / P3 / P3.3 / P4" },
      { label: "Brightness", value: "5,000 nits" },
      { label: "Display Sides", value: "3 Faces (270°)" },
      { label: "Input Voltage", value: "12V – 24V DC" },
      { label: "Battery Runtime", value: "6 – 8 Hours" },
      { label: "IP Rating", value: "IP65" },
      { label: "Control", value: "4G / GPS / Cloud" },
      { label: "Operating Temperature", value: "-20°C to +50°C" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "shop-window",
    slug: "shop-window-led",
    name: "Shop Window LED Display",
    series: "SW Series",
    category: "Advertising",
    image: "/images/products/shop-window-led-display.jpg",
    gallery: ["/images/products/shop-window-led-display.jpg"],
    description: "Specifically designed for retail window displays with ultra-high brightness to compete with direct sunlight.",
    longDescription: "Capture foot traffic with the SW Series. Unlike standard indoor screens, these displays feature ultra-high brightness levels (up to 6000 nits) to remain perfectly visible through glass panels even in mid-day sun. Sleek and professional for high-end retail.",
    features: [
      { title: "Direct Sunlight", description: "Vibrant colors even in windows facing the sun." },
      { title: "Auto-Dimming", description: "Smart sensors adjust brightness at night to save energy and meet local regulations." },
      { title: "Poster Design", description: "Slim aluminum frame with minimalist aesthetic for retail environments." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P2.5 - P5" },
      { label: "Brightness", value: "6000 nits" },
      { label: "Sizes", value: "55\" / 68\" / 80\"" },
      { label: "Maintenance", value: "Front Service" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "stadium-perimeter",
    slug: "stadium-perimeter-led",
    name: "Stadium Perimeter LED",
    series: "ST Series",
    category: "Advertising",
    image: "/images/products/outdoor-fixed-led-display.jpg",
    gallery: ["/images/products/outdoor-fixed-led-display.jpg", "/images/products/outdoor-rental-led-display.jpg"],
    description: "Professional athlete-safe LED perimeter boards for sports arenas — 7,000 nits, TV broadcast-ready 3840Hz refresh rate, IP65 outdoor-rated, and adjustable 0–90° bracket.",
    longDescription: "The ST Series Stadium Perimeter LED Display is the professional choice for Premier League, NBA, and international sports venues that demand both advertiser impact and athlete safety. Every board uses a soft rubber module mask on the player-facing surface and a padded foam top cover that meets international athlete safety standards for pitch-side installations. The 0–90° adjustable steel bracket repositions in under 2 minutes for different sports or camera angles without tools. At P6.67mm pitch with 7,000+ nits, every board is brilliant on 4K broadcast cameras and visible from the top tier of any stadium. Anti-curl and precision levelness ensure the entire perimeter appears perfectly straight when viewed through a telephoto broadcast lens. Individual boards can be removed and reinstalled in under 5 minutes for rapid pitch access and maintenance.",
    features: [
      { title: "Soft Rubber Athlete-Safe Mask", description: "Protective soft silicone face mask and padded foam top cover designed to meet international athlete safety standards for pitch-side use." },
      { title: "0–90° Adjustable Bracket", description: "Repositions for any sport or camera angle in under 2 minutes without tools — ideal for multi-sport arena timetables." },
      { title: "7,000 nits TV-Grade Brightness", description: "Fully visible from all grandstand tiers and perfectly exposed on 4K broadcast cameras without sensor compensation." },
      { title: "3840Hz Flicker-Free", description: "High refresh rate driving IC ensures zero flicker on all broadcast, streaming, action camera, and smartphone video." },
      { title: "IP65 Outdoor Certified", description: "Operates in rain, wind, and temperatures from -20°C to +60°C — built for open-air stadiums in all climates." },
      { title: "Anti-Curl Precision Levelness", description: "Board engineering guarantees the perimeter fence appears perfectly straight on telephoto broadcast lenses." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P6.67 – P10" },
      { label: "Brightness", value: "7,000+ nits" },
      { label: "Refresh Rate", value: "≥3840Hz" },
      { label: "Bracket Adjustment", value: "0° – 90° (Tool-Free)" },
      { label: "IP Rating", value: "IP65 Outdoor" },
      { label: "Cabinet Material", value: "Die-cast Aluminum" },
      { label: "Operating Temperature", value: "-20°C to +60°C" },
      { label: "Maintenance", value: "Front Removable (Under 5 Minutes)" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "mobile-bus",
    slug: "mobile-bus-led",
    name: "Mobile Bus LED Display",
    series: "MB Series",
    category: "Mobile",
    image: "/images/products/mobile-bus-led-display.jpg",
    gallery: ["/images/products/mobile-bus-led-display.jpg"],
    description: "High-visibility LED displays for buses and public transit vehicles — front, side, and rear configurations with 6,000 nits brightness, 4G fleet management, and GPS tracking.",
    longDescription: "The MB Series Mobile Bus LED Display maximises the advertising value of every vehicle in a public transit fleet. Buses travel every neighbourhood in a city daily, delivering unparalleled geographic advertising reach. Front and rear mounts are fixed with screws; side panel displays use dedicated mounting support brackets. At 6,000 nits, content is fully readable in all daylight. A built-in ambient light sensor manages brightness automatically. 4G group management allows the entire fleet's content to be updated simultaneously from one cloud dashboard, with GPS tracking providing campaign proof-of-play reports per-vehicle per-route. Wide-voltage input (12V–36V DC) is compatible with the electrical systems of all major bus manufacturers worldwide. Application areas include transit advertising, route information displays, school bus signage, and shuttle branding.",
    features: [
      { title: "Front, Side & Rear Configurations", description: "Full vehicle coverage: front destination LEDs, full-side advertising panels, and rear displays for following traffic." },
      { title: "6,000 nits Sunlight Visible", description: "Vivid and readable in all conditions — blazing noon sun, overcast skies, and coastal glare." },
      { title: "Vibration-Resistant Construction", description: "Anti-shock internal mounts and sealed PCBs handle the constant vibration of city bus routes without LED degradation." },
      { title: "4G Fleet Management", description: "Push updated content to the entire fleet simultaneously from a single cloud dashboard — separate schedules per vehicle if needed." },
      { title: "GPS Proof-of-Play Reports", description: "Per-vehicle, per-route campaign reports delivered automatically — show advertisers exactly where and when their ads ran." },
      { title: "Wide-Voltage 12V–36V Input", description: "Compatible with all major bus electrical systems worldwide. Integrated over-voltage protection ensures zero vehicle harm." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P3 – P6" },
      { label: "Brightness", value: "6,000 nits" },
      { label: "Protection", value: "IP65 Waterproof" },
      { label: "Input Voltage", value: "12V – 36V DC" },
      { label: "Control", value: "4G / GPS / WiFi" },
      { label: "Mounting", value: "Front / Side / Rear" },
      { label: "Operating Temperature", value: "-20°C to +60°C" },
      { label: "Lifespan", value: "100,000+ Hours" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "indoor-fixed",
    slug: "indoor-led-display",
    name: "Indoor Fixed LED Display",
    series: "IF Series",
    category: "Indoor",
    image: "/images/products/indoor-rental-led-display.jpg",
    gallery: ["/images/products/indoor-rental-led-display.jpg", "/images/products/digital-shelf-led-display.jpg"],
    description: "Premium fine-pitch indoor LED video wall for boardrooms, retail showrooms, control rooms, and broadcast studios — from P1.25mm for ultra-sharp close-range viewing.",
    longDescription: "The IF Series Indoor Fixed LED Display is the benchmark for fixed indoor video walls across corporate, retail, broadcast, and command-and-control environments. Fine pixel pitches from P1.25mm to P2.5mm deliver near-4K resolution at standard viewing distances, making the display indistinguishable from a commercial LCD monitor when viewed up close — but with no bezels, no brightness limits, and infinite scalability. The fanless passive-cooling design makes the IF Series whisper-quiet, critical for broadcast studios where ambient noise must be controlled. High greyscale support at low brightness ensures each frame maintains full colour depth even when the room is dim. One-person front maintenance: any module is replaced in under 60 seconds without tools using the magnetic tile system. Available in standard 16:9 aspect ratios or custom shapes and curvatures.",
    features: [
      { title: "Fine Pitch from P1.25mm", description: "P1.25–2.5mm range delivers near-4K resolution at typical boardroom and showroom viewing distances." },
      { title: "High Greyscale at Low Brightness", description: "Maintains full colour depth and detail at 20–100% brightness — prevents washed-out images in brightly lit rooms." },
      { title: "Fanless Silent Cooling", description: "Passive thermal management produces zero fan noise — essential for broadcast studios, auditoriums, and executive boardrooms." },
      { title: "60-Second Module Swap", description: "Magnetic front tile removal requires zero tools and just one person. Any module replaced in under 60 seconds." },
      { title: "Bezel-Free Scalability", description: "Seamlessly tile panels to any size, shape, or aspect ratio — from a 2m boardroom wall to a 20m control room display." },
      { title: "Wide 140° Viewing Angle", description: "140° horizontal and vertical viewing angle ensures every seat in any room has a perfect, undistorted view." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P1.25 – P2.5" },
      { label: "Brightness", value: "600 – 1,000 nits" },
      { label: "Refresh Rate", value: "≥3840Hz" },
      { label: "Viewing Angle", value: "H: 140° / V: 140°" },
      { label: "Cooling", value: "Fanless Passive" },
      { label: "Maintenance", value: "Front Magnetic (60 sec)" },
      { label: "Aspect Ratio", value: "Any (Custom)" },
      { label: "Lifespan", value: "100,000+ Hours" },
    ],
    models: [
      { name: "IF1.2", pitch: "1.25mm", ledType: "SMD1010", brightness: "600 nits", refreshRate: "3840Hz", powerMax: "500W/m²" },
      { name: "IF2.5", pitch: "2.5mm", ledType: "SMD1515", brightness: "800 nits", refreshRate: "3840Hz", powerMax: "450W/m²" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "rental-indoor",
    slug: "indoor-rental-led",
    name: "Indoor Rental LED Display",
    series: "RI Series",
    category: "Rental",
    image: "/images/products/indoor-rental-led-display.jpg",
    gallery: ["/images/products/indoor-rental-led-display.jpg"],
    description: "The professional standard for indoor event LED rental — lightweight 6.5kg cabinets, fast-lock system, 3840Hz refresh, and 30-second front module swap for exhibitions and stage productions.",
    longDescription: "The RI Series Indoor Rental LED Display is the event industry benchmark for stage backdrops, corporate presentations, product launches, and trade show video walls. Sharing the same proven 500×500mm and 500×1000mm cabinet standard as our outdoor rental line, the RI Series is tuned for indoor brightness levels at 800–1000 nits with 5000:1 black SMD contrast. Each cabinet weighs 6.5kg — one person can carry 3 panels at once, making fast large-scale setups achievable with minimal crew. The magnetic front tile system allows module swaps in under 30 seconds without tools — a critical capability for keeping live events running without audience-visible downtime. Cabinets support ±15° inner and outer arc for curved back walls and wrap-around stage designs. Both ground-stacking and ceiling-hanging configurations supported.",
    features: [
      { title: "6.5kg Ultra-Light Cabinets", description: "One person can carry 3 panels at once — accelerate crew setup for any event venue size." },
      { title: "30-Second Front Module Swap", description: "Magnetic front tile removal replaces any module in under 30 seconds, with zero tools, without interrupting the event." },
      { title: "5000:1 Black SMD Contrast", description: "Black-face SMD LEDs produce deep blacks and vivid highlights — cinema quality on any stage." },
      { title: "Auto-Lock Fast Assembly", description: "Single-action auto-lock joins panels with no tools. Two people build a 100m² wall in under 2 hours." },
      { title: "±15° Arc for Curved Stages", description: "Support for inner concave and outer convex curving creates dramatic curved backdrops and S-wave designs." },
      { title: "Hanging & Ground-Stack Modes", description: "Compatible with standard truss hanging and base ground-stack — any configuration for any venue." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P1.9 / P2.6 / P3.91" },
      { label: "Brightness", value: "800 – 1,000 nits" },
      { label: "Contrast Ratio", value: "5000:1" },
      { label: "Cabinet Size", value: "500×500mm / 500×1000mm" },
      { label: "Cabinet Weight", value: "6.5kg (500×500mm)" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Maintenance", value: "Front Magnetic (30 sec)" },
      { label: "Arc Flexibility", value: "±15° Concave/Convex" },
    ],
    models: [
      { name: "RI1.9", pitch: "1.9mm", ledType: "SMD1010Black", brightness: "800 nits", refreshRate: "3840Hz", powerMax: "600W/m²" },
      { name: "RI3.9", pitch: "3.91mm", ledType: "SMD1515Black", brightness: "1000 nits", refreshRate: "3840Hz", powerMax: "550W/m²" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },

  // ─── NEW PRODUCTS FROM hscled.com ─────────────────────────────────────────

  {
    id: "pharmacy-cross",
    slug: "pharmacy-cross-led-display",
    name: "Pharmacy Cross LED Display",
    series: "PC Series",
    category: "Advertising",
    image: "/images/products/pharmacy-cross-led-display.jpg",
    gallery: ["/images/products/pharmacy-cross-led-display.jpg"],
    description: "Full-color animated LED cross sign for pharmacies and clinics — IP65 waterproof, auto-dimming, single or double-sided, with dynamic video/animation capability.",
    longDescription: "The PC Series Pharmacy Cross LED Display is the definitive replacement for static illuminated cross signs on pharmacies, clinics, and health stores worldwide. While a traditional lightbox cross simply glows a static green or red, the PC Series plays full-color videos, animated health messages, temperature and humidity readings, and promotional content. Wall-mounted via expansion screws with no professional tools required, it can be opened from the front for simple maintenance. The built-in dimmer automatically adjusts brightness from blazing 6,000 nits in direct midday sun to a gentle ambient glow at night, eliminating light pollution concerns. IP65 dual-sided waterproof technology ensures the sign performs flawlessly through monsoons, extreme humidity, and high heat. Available in single or double-sided models, with optional round-edge corners and fully custom sizes for any shopfront.",
    features: [
      { title: "Full Color Dynamic Content", description: "RGB LEDs enable full-color videos, animations, temperature readings, promotional offers — dramatically more effective than static green neon crosses." },
      { title: "IP65 Dual Waterproof", description: "Dual-sided waterproof LED module technology provides IP65 protection against rain, humidity, and condensation year-round." },
      { title: "Built-In Auto Dimmer", description: "Ambient light sensor automatically adjusts brightness from 6,000 nits in daylight to subtle ambient levels at night — no manual controls needed." },
      { title: "Single & Double-Sided", description: "Available in single-sided and double-sided models ensuring visibility from both directions on any high street or corner pharmacy." },
      { title: "Plug & Play App Control", description: "Simple PC software and mobile app control. Manage content remotely with 4G optional module — video manual provided with every unit." },
      { title: "Easy Wall Installation", description: "Mounts with standard expansion screws — no specialist tools or electrician needed. Front-opening design for simple maintenance access." },
    ],
    specs: [
      { label: "LED Type", value: "Full Color RGB" },
      { label: "Brightness", value: "Up to 6,000 nits" },
      { label: "IP Rating", value: "IP65 Waterproof" },
      { label: "Memory", value: "4GB (up to 128GB)" },
      { label: "Sides", value: "Single / Double" },
      { label: "Control", value: "PC Software / App / 4G (Optional)" },
      { label: "Auto-Dimming", value: "Yes (Built-in Sensor)" },
      { label: "Installation", value: "Wall-Mounted (Expansion Screws)" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "outdoor-led-poster",
    slug: "outdoor-led-poster-display",
    name: "Outdoor LED Poster Display",
    series: "OP Series",
    category: "Advertising",
    image: "/images/products/outdoor-led-poster-display.jpg",
    gallery: ["/images/products/outdoor-led-poster-display.jpg"],
    description: "Weatherproof IP65 outdoor LED poster — 5,000 nits with NationStar LEDs, 3840Hz refresh, HDMI/4G/WiFi control, and freestanding / wall-mounted / hanging installation modes.",
    longDescription: "The OP Series Outdoor LED Poster Display is the outdoor counterpart to the industry-leading indoor digital poster — delivering all the plug-and-play simplicity of a digital banner in a fully weatherproof IP65 enclosure. Built with premium NationStar LEDs, the display achieves a balanced combination of 5,000 nits peak brightness and 3840Hz refresh rate, maintaining crystal-clear video quality under direct afternoon sunlight without compromising broadcast-readiness. High-contrast 5000:1 ratio and 16-bit grey processing ensure vivid, nuanced imagery even in complex lighting environments. The built-in brightness sensor adjusts automatically between day and night. Compatible with multiple installation styles: freestanding base, wall-mount bracket, ceiling-hang rail, or creative side-by-side splice configurations. Live content via HDMI or remote scheduling via 4G cloud — no PC required for auto-play mode.",
    features: [
      { title: "IP65 Full Weatherproofing", description: "Dual-sided waterproof LED module encapsulation and seamless panel splicing provide complete IP65 protection for outdoor use in any climate." },
      { title: "NationStar LED Brightness", description: "Premium NationStar LEDs deliver 5,000:1 contrast and vivid colour in direct sunlight — the gold standard for outdoor display components." },
      { title: "3840Hz High Refresh", description: "1920Hz/3840Hz selectable refresh rate with 16-bit grey processing — zero flicker on any camera, phone, or broadcast lens." },
      { title: "Live Broadcasting & Auto-Play", description: "HDMI live input for events; USB or cloud auto-play without any PC connection. Supports Windows software and mobile app." },
      { title: "Multiple Install Modes", description: "Freestanding, hanging, wall-mounted, horizontal, and creative splice configurations — adapts to any outdoor advertising location." },
      { title: "Auto Day/Night Dimming", description: "Integrated brightness sensor adjusts display power automatically from full sun brightness to low-impact evening levels." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P2.5 / P3 / P4 / P5" },
      { label: "Brightness", value: "5,000 nits" },
      { label: "Contrast Ratio", value: "5000:1" },
      { label: "Refresh Rate", value: "1920Hz / 3840Hz" },
      { label: "IP Rating", value: "IP65 Waterproof" },
      { label: "Control", value: "HDMI / LAN / WiFi / USB / 4G" },
      { label: "Installation", value: "Freestanding / Wall / Hang / Horizontal" },
      { label: "Auto-Dimming", value: "Yes (Built-in Sensor)" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "led-pillar",
    slug: "led-pillar-display",
    name: "LED Pillar Display",
    series: "LP Series",
    category: "Creative",
    image: "/images/products/can-shape-cylinder-led-display.jpg",
    gallery: ["/images/products/can-shape-cylinder-led-display.jpg", "/images/products/hexagon-led-screen.jpg"],
    description: "Slim, freestanding multi-sided LED display column — 16kg ultra-light, plug-and-play, single to 4-sided configurations for trade shows, retail stores, and hotel lobbies.",
    longDescription: "The LP Series LED Pillar Display replaces expensive, time-consuming printed banner stands with a dynamic, reusable LED advertising pillar that can change content instantly. At just 16kg per section and with integrated caster wheels available, a single person can transport and set up the display at any trade show, fair, restaurant, or retail venue. The most popular configuration is the 320×960mm single-sided column, but custom sizes up to 640×1120mm and 1 to 4-sided configurations are available without limitation. The built-in integrated processor is a true plug-and-play solution — no external video processor, no configuration complexity. Content is uploaded via WiFi app, LAN software, or USB — and with an optional 4G module, it can be updated remotely from any location. Front service design enables maintenance with a simple suction cup without any tools.",
    features: [
      { title: "16kg Ultra-Lightweight", description: "Each section weighs only 16kg — easily transported between venues and set up by a single person. Optional caster wheels available." },
      { title: "1 to 4-Sided Options", description: "Single, double, three, or four-sided configurations available — display content to one direction or 360° simultaneously." },
      { title: "320×960mm Most Popular Size", description: "Compact 320×960mm footprint fits anywhere. Custom sizes up to 640×1120mm available for larger retail spaces." },
      { title: "True Plug & Play", description: "Integrated processor with no external hardware needed. Upload content via USB immediately — zero configuration for non-technical users." },
      { title: "WiFi & 4G Remote Control", description: "Update content wirelessly via LAN/WiFi app from any device. Optional 4G for cloud-based remote management across multiple units." },
      { title: "Front Service with Suction Cup", description: "Freestanding design with front maintenance access. Any module replaced with a simple suction cup — no specialist tools required." },
    ],
    specs: [
      { label: "Popular Size", value: "320×960mm / 640×1120mm (Custom)" },
      { label: "Weight", value: "16kg per section" },
      { label: "Pixel Pitch", value: "P1.56 – P4" },
      { label: "Brightness", value: "800 – 1,200 nits" },
      { label: "Sides", value: "1 / 2 / 3 / 4 (Custom)" },
      { label: "Control", value: "WiFi / LAN / USB / 4G (Optional)" },
      { label: "Maintenance", value: "Front Service (Suction Cup)" },
      { label: "Installation", value: "Freestanding (Optional Wheels)" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "hexagon-led",
    slug: "hexagon-led-screen",
    name: "Hexagon LED Screen",
    series: "HX Series",
    category: "Creative",
    image: "/images/products/hexagon-led-screen.jpg",
    gallery: ["/images/products/hexagon-led-screen.jpg"],
    description: "Mesmerizing six-sided creative LED panel — P1.25mm to P4mm, plug-and-play, tiles together for football-shaped landmarks, shopping mall ceilings, and DJ stage effects.",
    longDescription: "The HX Series Hexagon LED Screen is the most versatile shaped display in the creative LED category. Each panel has six equal sides, creating a honeycomb-like visual language that is instantly distinctive from standard rectangular screens. Available in pixel pitches from P1.25mm to P4mm, with standard side lengths from 320mm (P2.5mm) to 600mm (P4mm). Multiple hexagons tile seamlessly for a large-scale honeycomb video wall, and 24 units combined form a football/soccer ball shape — famously popular for World Cup activations and sports bars. Synchronous and asynchronous playback modes: connect an HDMI source for live events, or load content to the built-in player via USB or WiFi for standalone looping. Applications range from nightclub ambience lighting, shopping mall ceiling art, trade show exhibits, and corporate lobby feature walls.",
    features: [
      { title: "Eight Pitch Options P1.25–P4", description: "Fine pitch from P1.25mm for close-range showroom use, up to P4mm for large public installations and stage backdrops." },
      { title: "Football Shape Configuration", description: "24 hexagon panels combine to form a 3D football/soccer ball shape — iconic for World Cup events, sports bars, and fan zones." },
      { title: "Custom Sizes & Combinations", description: "Standard 320–600mm side length, or fully custom. Tile any number together for honeycomb video walls of any dimension." },
      { title: "Plug & Play for Single Units", description: "No external processor needed for standalone units. Displays videos, photos, animations, and texts immediately on power-up." },
      { title: "Hanging & Wall-Mount Options", description: "Hang with top/rear hooks or wall-mount with rear screw holes — installs in any ceiling or wall orientation." },
      { title: "HDMI Live + WiFi Wireless", description: "HDMI for live broadcast at events; WiFi app for wireless content management across multiple panels from one device." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P1.25 / P1.8 / P2 / P2.5 / P3 / P4" },
      { label: "Side Lengths", value: "320mm (P2.5) to 600mm (P4) / Custom" },
      { label: "Brightness", value: "800 – 1,200 nits" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Control", value: "HDMI / WiFi / USB" },
      { label: "Installation", value: "Hanging / Wall-Mounted" },
      { label: "Shape Options", value: "Single / Honeycomb Array / Football (24pcs)" },
      { label: "IP Rating", value: "IP20 Indoor" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "round-circle-led",
    slug: "round-circle-led-display",
    name: "Round Circle LED Display",
    series: "RC Series",
    category: "Creative",
    image: "/images/products/sphere-led-display.jpg",
    gallery: ["/images/products/sphere-led-display.jpg", "/images/products/sphere-led.png"],
    description: "Custom circular LED screen for brand logos, stage centrepieces, and ceiling feature art — indoor from P1.25mm, outdoor IP65 from P3mm, single or double-sided.",
    longDescription: "The RC Series Round Circle LED Display transforms any brand logo, symbol, or artistic concept into a glowing circular media canvas. For retail, it makes company logos come alive — a 500mm P1.25mm circle behind a reception desk creates a premium brand impression that printed signs simply cannot match. For nightclubs and stages, larger 1–3m diameter outdoor IP65 circles create circular video art that is visible across the entire venue. Available in standard diameters from 500mm to 2.5m indoors, and up to 3m+ for outdoor models. Single or double-sided variants available — the double-sided model is ideal for suspended ceiling installations where the display is visible from both above and below. Content via plug-and-play USB, WiFi app, or HDMI live connection. Works 24/7 with passive or forced cooling depending on pitch and brightness requirements.",
    features: [
      { title: "Indoor from P1.25mm", description: "Ultra-fine P1.25mm pitch for stunning brand logo circles at close reception distances. Indistinguishable pixel quality at arm's length." },
      { title: "Outdoor IP65 from P3mm", description: "Fully waterproof outdoor circular LED from P3mm, P5mm, P8mm for exterior signage, plazas, and festival stages." },
      { title: "500mm to 3m+ Custom Diameters", description: "Standard diameters from 500mm for desk-side logos up to 3m+ outdoor ceiling installations — any size manufactured to order." },
      { title: "Single or Double-Sided", description: "Double-sided model suspends from ceiling — visible from above and below simultaneously. Ideal for atriums and suspended stage rigs." },
      { title: "Brand Logo Perfection", description: "Pixel-perfect circular masking preserves logo geometry. No visible rectangular borders — pure circular content with crisp edges." },
      { title: "Plug & Play + Live HDMI", description: "USB auto-play for standalone looping; HDMI for live event broadcast; WiFi/4G for remote cloud management." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P1.25 – P3 (Indoor) / P3 – P8 (Outdoor)" },
      { label: "Diameter", value: "500mm – 3m+ (Custom)" },
      { label: "Sides", value: "Single / Double" },
      { label: "IP Rating", value: "IP20 (Indoor) / IP65 (Outdoor)" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Control", value: "USB / WiFi / HDMI / 4G (Optional)" },
      { label: "Installation", value: "Hanging / Wall-Mounted" },
      { label: "Operation", value: "24/7 Continuous" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "outdoor-led-totem",
    slug: "outdoor-led-totem-display",
    name: "Outdoor LED Totem Display",
    series: "OT Series",
    category: "Advertising",
    image: "/images/products/outdoor-led-totem-display.jpg",
    gallery: ["/images/products/outdoor-led-totem-display.jpg"],
    description: "Freestanding outdoor LED totem with tempered glass protection, built-in speakers, WiFi/4G cloud management, and front-service access — the premium street-level advertising kiosk.",
    longDescription: "The OT Series Outdoor LED Totem Display is the premium freestanding digital kiosk for outdoor advertising, wayfinding, and public information. Unlike wall-mounted outdoor displays, the totem stands independently on a weighted base — deployable at any outdoor location without permanent structural fixings. High-brightness LEDs maintain vivid imagery under direct sunlight, with optional tempered safety glass over the display face for vandalism and impact protection. A built-in speaker enables audio announcements or branded audio content. The display is available in single-sided, dual-sided, or multi-sided configurations to maximise the advertising exposure from every direction at high-foot-traffic locations. The 4G controller enables a network of hundreds of totems to be managed simultaneously from one cloud dashboard — ideal for city-wide retail chains, transport hubs, and public information networks.",
    features: [
      { title: "Freestanding No-Drill Install", description: "Weighted base allows deployment at any outdoor location without permanent structural fixings, drilling, or planning permission." },
      { title: "Tempered Glass Vandal Protection", description: "Optional tempered safety glass overlay protects the LED face from impact, vandalism, and environmental debris in public spaces." },
      { title: "Built-In Speaker System", description: "Integrated speaker delivers audio content, announcements, and branded sound experiences alongside the visual display." },
      { title: "Single, Dual, or Multi-Sided", description: "Available in 1, 2, or 3+ sided configurations to maximise advertising reach at busy intersections and plaza locations." },
      { title: "4G Cloud Fleet Management", description: "Manage hundreds of totems city-wide from one dashboard. Upload new campaigns to all units simultaneously — fully wireless." },
      { title: "Front Maintenance Access", description: "Front-service design allows module replacement without moving the totem or accessing the rear — minimises downtime." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P3 – P10 (Outdoor)" },
      { label: "Brightness", value: "5,000 – 8,000 nits" },
      { label: "IP Rating", value: "IP65 Outdoor" },
      { label: "Sides", value: "1 / 2 / 3+ (Custom)" },
      { label: "Audio", value: "Built-in Speaker (Optional)" },
      { label: "Protection", value: "Tempered Glass (Optional)" },
      { label: "Control", value: "WiFi / App / 4G Cloud" },
      { label: "Maintenance", value: "Front Service" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "triangle-led",
    slug: "triangle-led-display",
    name: "Triangle LED Display",
    series: "TR Series",
    category: "Creative",
    image: "/images/products/triangle-led-display.jpg",
    gallery: ["/images/products/triangle-led-display.jpg"],
    description: "Custom triangular LED panel for geometric video walls, architectural installations, stage lighting, and immersive event environments — any angle, any combination.",
    longDescription: "The TR Series Triangle LED Display enables architects, event designers, and brand experience agencies to break free from rectangular screen constraints entirely. Equilateral or right-angled triangular panels can be combined in unlimited configurations to create diamond shapes, arrow patterns, hexagonal mosaics, and entirely custom geometric video installations. Indoor pixel pitches from P1.8mm to P3mm deliver high resolution content at typical gallery and showroom viewing distances. Outdoor models at P3mm–P6mm are IP65 rated. Synchronous controller support enables large multi-panel installations to run perfectly synchronised video content across the entire geometric arrangement. Hanging or wall-mounting with rear screw holes. Popular for nightclub geometric ceiling art, festival stage backdrops, retail feature walls, and museum interactive installations.",
    features: [
      { title: "Any Geometric Combination", description: "Triangular panels tile to form diamonds, arrows, hexagons, stars, and any freeform geometric pattern — unlimited configuration possibilities." },
      { title: "Indoor P1.8–P3 / Outdoor P3–P6", description: "High resolution fine-pitch for close-viewing showrooms; IP65 outdoor models for exterior facades and festival stages." },
      { title: "Synchronised Multi-Panel Video", description: "Synchronous controller system runs perfectly timed video across unlimited triangular panels as one unified display canvas." },
      { title: "Custom Size & Angle", description: "Equilateral, right-angled, and isosceles triangle configurations available. Any side length manufactured to specification." },
      { title: "Hanging & Wall-Mounted", description: "Rear hook points for ceiling suspension; rear screw holes for flush wall mounting — both orientations in the same unit." },
      { title: "Stage & Nightclub Lighting Effect", description: "With strobe-mode compatible driving ICs and programmable refresh, creates dramatic pulsing geometric light art for live events." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P1.8 – P3 (Indoor) / P3 – P6 (Outdoor)" },
      { label: "Shape", value: "Equilateral / Right-Angle / Isosceles (Custom)" },
      { label: "Brightness", value: "800 – 1,000 nits (Indoor) / 5,000 nits (Outdoor)" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "IP Rating", value: "IP20 (Indoor) / IP65 (Outdoor)" },
      { label: "Control", value: "HDMI / WiFi / USB / Synchronous" },
      { label: "Installation", value: "Hanging / Wall-Mounted" },
      { label: "Configuration", value: "Single / Mosaic Array / Custom Geometric" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "dj-booth-led",
    slug: "dj-booth-led-screen",
    name: "DJ Booth LED Screen",
    series: "DJ Series",
    category: "Rental",
    image: "/images/products/dj-booth-led-screen.jpg",
    gallery: ["/images/products/dj-booth-led-screen.jpg"],
    description: "Custom-shaped LED video screen for DJ booths, nightclubs, and live music venues — immersive 270° visual environments with real-time audio-reactive content capability.",
    longDescription: "The DJ Series DJ Booth LED Screen is the defining visual feature of any premier nightclub or live music venue. Standard flat rectangular screens behind a DJ booth are a missed opportunity — the DJ Series wraps around the booth in custom L-shapes, U-shapes, and curved configurations that create a truly immersive 270° visual environment the audience can't look away from. Fine pitch panels from P1.8mm to P3.91mm maintain sharp imagery even at close stage-adjacent viewing. A built-in sync trigger input allows the LED controller to receive the DJ's audio BPM signal and pulse content to the beat in real time — no additional hardware needed. Each panel is the standard 500×500mm rental cabinet, meaning it integrates directly with any existing outdoor or indoor rental inventory. Same-day setup by two people; front magnetic module access for live-event maintenance.",
    features: [
      { title: "Custom Booth Shape Configurations", description: "L-shape, U-shape, curved, and multi-panel configurations wrap around any DJ booth design for a 270° immersive visual stage." },
      { title: "Audio-Reactive Beat Sync", description: "Built-in BPM trigger input allows LED controller to synchronise content pulses to the DJ's audio signal in real time." },
      { title: "Standard Rental Cabinet Size", description: "500×500mm industry-standard cabinet integrates seamlessly with any existing rental LED inventory — no proprietary equipment." },
      { title: "Fine Pitch P1.8–P3.91", description: "Sharp, vivid imagery at typical DJ-to-crowd distances. Black-face SMD LEDs produce deep contrast for dramatic nightclub environments." },
      { title: "Fast 2-Person Setup", description: "Auto-lock cabinet system and standard truss hanging enables two people to build a complete booth installation in under 2 hours." },
      { title: "Front Magnetic Module Access", description: "Any module swappable from the front during live events without interrupting the show — critical for multi-night club residencies." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P1.8 / P2.6 / P3.91" },
      { label: "Cabinet Size", value: "500×500mm (Standard Rental)" },
      { label: "Brightness", value: "1,000 nits" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Audio Sync", value: "BPM Trigger Input" },
      { label: "Configuration", value: "L-Shape / U-Shape / Curved / Custom" },
      { label: "Maintenance", value: "Front Magnetic (Live-Event Safe)" },
      { label: "Setup Time", value: "Under 2 Hours (2 Person)" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "light-pole-led",
    slug: "light-pole-led-display",
    name: "Light Pole LED Display",
    series: "PL Series",
    category: "Advertising",
    image: "/images/products/light-pole-led-display.png",
    gallery: ["/images/products/light-pole-led-display.png"],
    description: "Smart city LED advertising screen for street lamp poles — 5,000 nits, IP65, 4G cloud control, ambient sensor, and tool-free pole-clamp installation for municipal and retail districts.",
    longDescription: "The PL Series Light Pole LED Display transforms existing street lamp infrastructure into a smart city digital advertising network. Instead of erecting new billboard structures, pole displays clamp directly to any standard round or square lamp pole with a tool-free adjustable bracket — deployable across an entire city district in days rather than weeks. Each unit features 5,000 nits brightness for clear visibility in all daylight conditions, an IP65-rated weatherproof enclosure rated for -40°C to +60°C operation, and a built-in 4G module for cloud content management across the entire network. An ambient light sensor dims each unit automatically at night. GPS tracking enables geo-targeted content scheduling by street, zone, or proximity to retail anchor stores. Single or double-sided models available. Power draw from the existing pole circuit — no additional electrical infrastructure required.",
    features: [
      { title: "Tool-Free Pole Clamp Install", description: "Adjustable pole clamp fits round or square lamp posts of any diameter. No drilling, no concrete — deployed in minutes per pole." },
      { title: "5,000 nits Smart City Bright", description: "Vivid and readable from pedestrians and passing vehicles in all daylight and weather conditions on any street type." },
      { title: "IP65 -40°C to +60°C", description: "Full municipal-grade weatherproofing for permanent outdoor deployment in all climates — from desert heat to arctic cold." },
      { title: "4G Network Fleet Control", description: "Manage unlimited poles across an entire city from one cloud dashboard. Schedule and push content to any zone or individual pole instantly." },
      { title: "GPS Zone-Targeted Content", description: "Serve location-specific ads based on street, district, or proximity to specific retailers, transport hubs, or event venues." },
      { title: "Pole Circuit Power Share", description: "Draws power directly from the existing lamp pole circuit — no new electrical cabling or additional infrastructure investment." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P4 – P6 (Outdoor)" },
      { label: "Brightness", value: "5,000 nits" },
      { label: "IP Rating", value: "IP65 Weatherproof" },
      { label: "Sides", value: "Single / Double" },
      { label: "Operating Temperature", value: "-40°C to +60°C" },
      { label: "Control", value: "4G Cloud / WiFi / GPS" },
      { label: "Installation", value: "Pole Clamp (Tool-Free)" },
      { label: "Auto-Dimming", value: "Yes (Built-in Sensor)" },
    ],
    buyable: false,
    price: null,
    unit: null,
  },
  {
    id: "digital-shelf-led",
    slug: "digital-shelf-led-display",
    name: "Digital Shelf LED Display",
    series: "DS Series",
    category: "Indoor",
    image: "/images/products/digital-shelf-led-display.jpg",
    gallery: ["/images/products/digital-shelf-led-display.jpg"],
    description: "Ultra-slim LED shelf-edge display for supermarkets, pharmacies, and electronics retailers — dynamic price, promotion, and product content updated wirelessly in real time.",
    longDescription: "The DS Series Digital Shelf LED Display is the next evolution of the traditional paper shelf label. Ultra-slim at under 15mm depth, each strip display mounts magnetically or with standard rail clips to any existing retail shelving system in seconds. Content — including dynamic pricing, countdown promotions, nutritional information, and brand videos — is updated wirelessly via WiFi or Bluetooth from a central management tablet or PC, eliminating the cost and labour of printing, distributing, and replacing paper labels. Multiple displays can be grouped by category, aisle, or individual SKU for precision control. A store manager can update all pricing across a 50,000 sq ft supermarket in under 3 minutes from any device. The display's warm-white or full-colour model options make it suitable for premium product presentation in electronics, fashion, cosmetics, and FMCG.",
    features: [
      { title: "Under 15mm Ultra-Slim Depth", description: "Clips to any existing retail shelf rail or mounts magnetically — no structural modifications, no additional shelf hardware needed." },
      { title: "Real-Time Wireless Price Updates", description: "Update all shelf prices across an entire store in under 3 minutes via WiFi or Bluetooth from a central management device." },
      { title: "Dynamic Promotions & Countdown", description: "Display real-time countdown timers for flash sales, animated promotion banners, and product recommendation content." },
      { title: "Warm White & Full Colour Models", description: "Clean warm-white text display for price labels; full RGB model for brand campaigns, video content, and product media." },
      { title: "Category & Individual SKU Control", description: "Group displays by aisle, category, or individual product for precision campaign targeting within any retail environment." },
      { title: "Universal Shelf Compatibility", description: "Magnetic and clip-rail mounting systems compatible with all standard retail shelving — Tegometall, MARC, and custom systems." },
    ],
    specs: [
      { label: "Pixel Pitch", value: "P1.25 – P2.5" },
      { label: "Depth", value: "Under 15mm" },
      { label: "Display Models", value: "Warm White / Full RGB" },
      { label: "Mounting", value: "Magnetic / Clip-Rail" },
      { label: "Control", value: "WiFi / Bluetooth / LAN" },
      { label: "Update Speed", value: "Entire Store Under 3 Minutes" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Compatibility", value: "All Standard Retail Shelving Systems" },
    ],
    buyable: false,
    price: null,
    unit: null,
  }
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug)
}

